version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bakery_web
    ports:
      - "7002:7002"
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      DATABASE_NAME: ${DATABASE_NAME}
      ALLOW_ORIGIN: ${ALLOW_ORIGIN}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      HOST: ${HOST}
      DB_PORT: ${DB_PORT}

  db:
    image: postgres:latest
    container_name: bakery_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: bakery_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "bakery@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - db

  trivy:
    image: aquasec/trivy:latest
    container_name: bakery_trivy_scan
    command: >
      image --exit-code 0 --no-progress --severity HIGH,CRITICAL bakery_web
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TRIVY_DISABLE_VEX_NOTICE: "true"

volumes:
  db_data:
