services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bakery_web
    ports:
      - "7002:8080"  # Host port 7002 maps to container port 8080 (matching app.listen port)
    environment:
      PORT: 8080
      NODE_ENV: ${NODE_ENV}
      DATABASE_NAME: ${DATABASE_NAME}
      ALLOW_ORIGIN: ${ALLOW_ORIGIN}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      HOST: db  # This should point to db container hostname for DB connection
      DB_PORT: 5432

  db:
    image: postgres:latest
    container_name: bakery_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: bakery_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "bakery@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - db

  trivy:
    image: aquasec/trivy:latest
    container_name: bakery_trivy_scan
    command: >
      image --exit-code 0 --no-progress --severity HIGH,CRITICAL bakery_web
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TRIVY_DISABLE_VEX_NOTICE: "true"

volumes:
  db_data:
