global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'bakery_web'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:7002']   # 👈 your app container and port
