apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-backend.fullname" . }}{{- if eq .Values.strategy.type "blueGreen" }}-{{ .Values.strategy.blueGreen.activeColor }}{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "node-backend.name" . }}
    helm.sh/chart: {{ include "node-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "node-backend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}{{- if eq .Values.strategy.type "blueGreen" }}-{{ .Values.strategy.blueGreen.activeColor }}{{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "node-backend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}{{- if eq .Values.strategy.type "blueGreen" }}-{{ .Values.strategy.blueGreen.activeColor }}{{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.prometheus.scrape.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.prometheus.scrape.path | quote }}
        prometheus.io/port: {{ .Values.service.targetPort | quote }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "node-backend.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

